package calculator.functions;

import calculator.Expression;
import calculator.atoms.AtomType;
import visitor.Visitor;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import calculator.Notation;
import visitor.Printer;

/**
 * Expression type for pseudo-random calculator functions.
 */
public final class RandomFunction implements Expression {

    private final AtomType type;
    private final List<Expression> args;

    /**
     * Constructs a new {@code RandomFunction} with the specified atom type and arguments.
     * 
     * @param type the type of number this function will generate (e.g., INTEGER, RATIONNAL)
     * @param args the list of arguments provided to the random function (like max bounds or seeds)
     */
    private RandomFunction(AtomType type, List<Expression> args) {
        this.type = type;
        this.args = args;
    }

    /**
     * Gets the expected exact number type for this random function output.
     * 
     * @return the {@link AtomType} representing the type of number generated by this function
     */
    public AtomType getType() {
        return type;
    }

    /**
     * Gets the arguments associated with this random function.
     * These typically include the maximum threshold or the generation seed.
     * 
     * @return a list of {@link Expression} arguments
     */
    public List<Expression> getArgs() {
        return args;
    }

    /**
     * Checks if this random function evaluates a specific seed provided as argument.
     * 
     * @return {@code true} if a seed block is provided among the arguments, {@code false} otherwise
     */
    public boolean hasSeed() {
        return (type == AtomType.INTEGER && args.size() == 2) ||
               (type == AtomType.RATIONNAL && args.size() == 2) ||
               (type == AtomType.REAL && args.size() == 1) ||
               (type == AtomType.COMPLEX && args.size() == 1);
    }

    /**
     * Creates a random function expression that generates an integer between 0 and {@code max} inclusive.
     * 
     * @param max the maximum bound expression
     * @return a new {@code RandomFunction} configured for integer generation
     */
    public static RandomFunction randomInteger(Expression max) {
        List<Expression> args = new ArrayList<>();
        args.add(max);
        return new RandomFunction(AtomType.INTEGER, args);
    }

    /**
     * Creates a random function expression that generates an integer between 0 and {@code max} inclusive,
     * using a specified numeric {@code seed}.
     * 
     * @param seed the seed block expression
     * @param max the maximum bound expression
     * @return a new {@code RandomFunction} configured for seeded integer generation
     */
    public static RandomFunction randomInteger(Expression seed, Expression max) {
        List<Expression> args = new ArrayList<>();
        args.add(seed);
        args.add(max);
        return new RandomFunction(AtomType.INTEGER, args);
    }

    /**
     * Creates a random function expression that generates a rational number where the numerator and
     * denominator are selected randomly between 0 and {@code max} inclusive (with denominator > 0).
     * 
     * @param max the maximum bound expression
     * @return a new {@code RandomFunction} configured for rational generation
     */
    public static RandomFunction randomRational(Expression max) {
        List<Expression> args = new ArrayList<>();
        args.add(max);
        return new RandomFunction(AtomType.RATIONNAL, args);
    }

    /**
     * Creates a random function expression that generates a rational number using a specified {@code seed},
     * bounding the numerator and denominator up to {@code max} inclusive (with denominator > 0).
     * 
     * @param seed the seed block expression
     * @param max the maximum bound expression
     * @return a new {@code RandomFunction} configured for seeded rational generation
     */
    public static RandomFunction randomRational(Expression seed, Expression max) {
        List<Expression> args = new ArrayList<>();
        args.add(seed);
        args.add(max);
        return new RandomFunction(AtomType.RATIONNAL, args);
    }

    /**
     * Creates a random function expression that generates a real number between 0 (inclusive) and 1 (exclusive).
     * 
     * @return a new {@code RandomFunction} configured for real generation
     */
    public static RandomFunction randomReal() {
        return new RandomFunction(AtomType.REAL, new ArrayList<>());
    }

    /**
     * Creates a random function expression that generates a real number between 0 (inclusive) and 1 (exclusive),
     * using a specified numeric {@code seed}.
     * 
     * @param seed the seed block expression
     * @return a new {@code RandomFunction} configured for seeded real generation
     */
    public static RandomFunction randomReal(Expression seed) {
        List<Expression> args = new ArrayList<>();
        args.add(seed);
        return new RandomFunction(AtomType.REAL, args);
    }

    /**
     * Creates a random function expression that generates a complex number where real and imaginary parts
     * are bounded between 0 (inclusive) and 1 (exclusive).
     * 
     * @return a new {@code RandomFunction} configured for complex generation
     */
    public static RandomFunction randomComplex() {
        return new RandomFunction(AtomType.COMPLEX, new ArrayList<>());
    }

    /**
     * Creates a random function expression that generates a complex number between 0 (inclusive) and 1 (exclusive),
     * using a specified numeric {@code seed}.
     * 
     * @param seed the seed block expression
     * @return a new {@code RandomFunction} configured for seeded complex generation
     */
    public static RandomFunction randomComplex(Expression seed) {
        List<Expression> args = new ArrayList<>();
        args.add(seed);
        return new RandomFunction(AtomType.COMPLEX, args);
    }

    @Override
    public void accept(Visitor v) {
        v.visit(this);
    }

    @Override
    public String toString() {
        Printer p = new Printer();
        this.accept(p);
        return p.getResult();
    }

    public String toString(Notation n) {
		Printer p = new Printer(n);
		this.accept(p);
		return p.getResult();
	}

	@Override
	public boolean equals(Object o) {
		if (o == null)
			return false;
		if (this == o)
			return true;
		if (getClass() != o.getClass())
			return false;
        RandomFunction that = (RandomFunction) o;
        return type == that.type && Objects.equals(args, that.args);
	}

    @Override
	public int hashCode() {
		return Objects.hash(type, args);
	}
}
