services: 
  backend:
    # in backend folder
    build: backend/.
    # port to use
    env_file : "backend.env"
    ports:
      - "1523:1523"
    #healthcheck to check if the API has finished booting up 
    healthcheck:
      # tests if the backend server respond
      test: ["CMD-SHELL","curl  http://localhost:1523/api/ping | grep pong || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

  front:
    build: frontend/.
    # waits for the backend to respond
    depends_on:
      backend:
        condition: service_healthy
        restart: true
    ports:
      - "1626:8080"
