package calculator;

import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTree;

public class Parser {

    /**
     * Analyze a string input and return an Expression object representing the parsed expression.
     * 
     */
    public Expression parse(String inputStr) {
        // Creation of a CharStream from the input string
        CharStream input = CharStreams.fromString(inputStr);

        // Lexer generated by ANTLR (calculatorLexer) to tokenize the input
        calculatorLexer lexer = new calculatorLexer(input);
        CommonTokenStream tokens = new CommonTokenStream(lexer);

        // Parser generated by ANTLR (calculatorParser) to create a parse tree from the tokens
        calculatorParser parser = new calculatorParser(tokens);
        ParseTree tree = parser.complete();

       // Visit the tree to build the Expression
        ParserVisitor visitor = new ParserVisitor();
        return visitor.visit(tree);
    }
}
