package calculator;

import org.antlr.v4.runtime.tree.TerminalNode;

/**
 * Visitor class that extends the base visitor generated by ANTLR.
 * This class will be responsible for traversing the parse tree and constructing the corresponding Expression objects based on the rules defined in the grammar.
 */
public class ParserVisitor extends calculatorBaseVisitor<Expression> {

    @Override
    public Expression visitComplete(calculatorParser.CompleteContext ctx) {
        return visit(ctx.getChild(0));
    }

    @Override
    public Expression visitExpressionPRE(calculatorParser.ExpressionPREContext ctx) {
        
    }

}
