package calculator;

import org.antlr.v4.runtime.tree.TerminalNode;

/**
 * Visitor class that extends the base visitor generated by ANTLR.
 * This class will be responsible for traversing the parse tree and constructing the corresponding Expression objects based on the rules defined in the grammar.
 */
public class ParserVisitor extends calculatorBaseVisitor<Expression> {

    private Expression buildOperation(String opString, List<Expression> args) {
        try {
            switch (opString) {
                case "+": return new Plus(args);
                case "-": return new Minus(args);
                case "*": return new Times(args);
                case "/": return new Divides(args);
                default:  throw new IllegalArgumentException("Unknown operator: " + opString);
            }
        } catch (IllegalConstruction e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public Expression visitComplete(calculatorParser.CompleteContext ctx) {
        return visit(ctx.getChild(0));
    }

    @Override
    public Expression visitExpressionPRE1(calculatorParser.ExpressionPRE1Context ctx) {
        Expression left = visit(ctx.expressionPRE(0));
        Expression right = visit(ctx.expressionPRE(1));
        return buildOperation(ctx.operator().getText(), Arrays.asList(left, right));
    }

    @Override
    public Expression visitExpressionPRE2(calculatorParser.ExpressionPRE2Context ctx) {
        Expression first = visit(ctx.expressionPRE(0));
        List<Expression> args = new ArrayList<>();
        args.add(first);
        // temporary work, doesnt work
        for (int i = 1; i < ctx.expressionPRE().size(); i++) {
            args.add(visit(ctx.expressionPRE(i)));
        }
        return buildOperation(ctx.operator().getText(), args);
    }

}
